### ISSUE TITLE
Cannot sign with a locked key pair

### ISSUE THREAD

**Issue by flupine** [paritytech/substrate-contracts-explorer#189] opened 2022-01-24 16:19 UTC
Hello, 
I have this error  when I try to use an account who is on the PolkadotJS extension for creating my contract.

**Error: Cannot sign with a locked key pair**

How I can resolve that, because my PolkadotJS extension dosen't ask for password or any authorization and I think this is where the error come from.

**Comment by statictype** [comment] 2022-01-24 16:35
we are working on that. you should be able to use development accounts for the local node

duplicate of https://github.com/paritytech/substrate-contracts-explorer/issues/181

**Closed by statictype** 2022-01-24 16:35 UTC
